# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be9d47de20ad898cb247b04d038e0d0338b3302e0539a8874d2be207e1055c685f8f5579887ad23278422f7819d3b5c4f2349be4c2a2d012abf60600bd64729d

test:
  secret_key_base: 8c21105fa8dd3c5eebfdc79e4638f6cb887ffb80c4234829fcd5d8c2db22b9519cd2de0c679a8cd820594f1434bdf6d12f10ca6d449b7f07d793cb743249cee8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
